# Generated by Django 4.1.7 on 2023-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_cat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
