# Generated by Django 4.1.7 on 2023-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashionapp', '0002_alter_product_pro_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_des',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
