# Generated by Django 4.1.7 on 2023-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashionapp', '0003_category_cat_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
