# Generated by Django 4.1.7 on 2023-10-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efashionapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=100, null=True)),
                ('password1', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=300, null=True)),
                ('address2', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('postalcode', models.IntegerField(null=True)),
            ],
        ),
    ]
