# Generated by Django 4.1.7 on 2023-10-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efashionapp', '0010_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
