from django.urls import path
from . import views

urlpatterns = [
    path('adminindex',views.adminindex1,name='adminindex1'),
    path('producttable',views.producttable1,name='producttable1'),
    path('carttable',views.carttable1,name='carttable1'),
    path('categorytable',views.categorytable1,name='categorytable1'),
    path('addcategoryview',views.addcategoryview,name='addcategoryview1'),
    path('addcategory',views.addcategory1,name='addcategory1'),
    path('addproduct',views.addproduct1,name='addproduct1'),
    path('addproductview',views.addproductview,name='addproductview1'),
    path('proedit/<int:eid>/',views.proedit,name='proedit1'),
    path('prodelete/<int:did>/',views.prodelete,name='prodelete1'),
    path('proupdate/<int:uid>/',views.proupdate,name='proupdate1'),
    path('catedit/<int:eid>/',views.catedit,name='catedit1'),
    path('catdelete/<int:did>/',views.catdelete,name='catdelete1'),
    path('catupdate/<int:uid>/',views.catupdate,name='catupdate1'),
    path('',views.login1,name='login1'),
    path('register',views.register1,name='register1'),
    path('registerview',views.registerview,name='registerview1'),
    path('loginview',views.loginview,name='loginview1'),
    path('usermain',views.usermain,name='usermain1'),
    path('about',views.about,name='about1'),
    path('shop/<str:category>/',views.shop,name='shop1'),
    path('product/<int:product_id>/',views.productdetails,name='productdetails1'),
    path('cart',views.cart1,name='cart1'),
    path('cartview/<int:cid>/',views.cartview,name='cartview1'),
    path('cartdelete/<int:cdid>/',views.cartdelete,name='cartdelete1'),
    path('cartupdate',views.cartupdate,name='cartupdate'),
    path('checkout',views.checkout,name='checkout1'),
    path('checkoutview',views.checkoutview,name='checkoutview1'),
    path('contact',views.contactus,name='contact1'),
    path('contacttable',views.contacttable1,name='contacttable1'),
    path('contacttview',views.contactview,name='contactview1'),
    path('logout',views.logout,name='logout1'),
    path('checkdelete/<int:did>/',views.checkdelete,name='checkdelete1'),
   
]